name = 'Ascon-128a_x4'

[rtl]
generator.command = "xeda run bsc --design-name Ascon --design-overrides rtl.parameters.UNROLL_FACTOR=4 rtl.parameters.ASCON128A=1 --settings verilog_out_dir=${DESIGN_ROOT}/gen_rtl/Ascon128a/x4"
generator.sources = ["*.bsv", "*/*.bsv"]
sources = ["gen_rtl/Ascon128a/x4/lwc.v"]
top = "lwc"
clock.port = "clk"

[tb]
sources = ["ascon128a_tb.py"]
cocotb = true

# sources = [
#     "../../LWC/hardware/LWC_config_32.vhd",
#     "../../LWC/hardware/LWC_rtl/NIST_LWAPI_pkg.vhd",
#     "../../LWC/hardware/LWC_tb/LWC_TB.vhd",
# ]

# [lwc]
# aead.algorithm = 'ascon128av12'
# aead.key_reuse = false
# hash.algorithm =  'asconhashav12'
# block_bits = { AD = 128, PT = 128, HM = 128 }

[flows.vivado_synth]
fpga.part = "xc7a100tftg256-2L"
# clock.freq = "100MHz"
flatten_hierarchy = "full"
synth.strategy = "Flow_AreaOptimized_high"
synth.steps.SYNTH_DESIGN.ARGS.GLOBAL_RETIMING = "on"
impl.strategy = "Performance_ExplorePostRoutePhysOpt"
impl.steps.POST_ROUTE_PHYS_OPT_DESIGN.IS_ENABLED = "true"
