name = 'Ascon-128_x1'

[rtl]
generator = "xeda run bsc --design-name Ascon --design-overrides rtl.parameters.UNROLL_FACTOR=1 --settings verilog_out_dir=${design_root}/gen_rtl/x1"
sources = [
    "gen_rtl/x1/lwc.v",
]
top = "lwc"
clock.port = "clk"

[tb]
sources = ["asconTb.py"]
cocotb = true

# sources = [
#     "../../LWC/hardware/LWC_config_32.vhd",
#     "../../LWC/hardware/LWC_rtl/NIST_LWAPI_pkg.vhd",
#     "../../LWC/hardware/LWC_tb/LWC_TB.vhd",
# ]

[lwc]
aead.algorithm = 'ascon128v12'
aead.key_reuse = false
hash.algorithm =  'asconhashv12'
block_bits = { AD = 64, PT = 64, HM = 64 }
