name = 'Ascon-128_x1'

[rtl]
generator = "xeda run bsc --design-name Ascon --design-overrides rtl.parameters.UNROLL_FACTOR=2 --settings verilog_out_dir=${design_root}/gen_rtl/x2"
sources = [
    "gen_rtl/x2/lwc.v",
]
top = "lwc"
clock.port = "clk"

[tb]
sources = ["asconTb.py"]
cocotb = true
