[[project]]
name = "Ascon"
description = "Ascon AEAD+HASH"
author = "Kamyar Mohajerani"

[[design]]
name = 'AsconCipher'

[design.lwc]
algorithm = ['ascon128v12']

[design.rtl]
sources = [
    "../bluelight/Bus/BusDefines.bsv",
    "../bluelight/Bus/BusFIFO.bsv",
    "../bluelight/Bus/Bus.bsv",
    "../bluelight/LwcApiDefines.bsv",
    "../bluelight/CryptoCore.bsv",
    "../bluelight/LwcApi.bsv",
    'AsconRound.bsv',
    'AsconCipher.bsv',
]
top = 'mkAsconCipher'

[design.tb]
sources = ["cipherTb.py"]
cocotb = true

[[design]]
name = 'Ascon'

[design.rtl]
sources = [
    "../bluelight/Bus/BusDefines.bsv",
    "../bluelight/Bus/BusFIFO.bsv",
    "../bluelight/Bus/Bus.bsv",
    "../bluelight/LwcApiDefines.bsv",
    "../bluelight/BluelightUtils.bsv",
    "../bluelight/CryptoCore.bsv",
    "../bluelight/LwcApi.bsv",
    'AsconRound.bsv',
    'AsconCipher.bsv',
    'InputLayer.bsv',
    'OutputLayer.bsv',
    'Ascon.bsv',
    'AsconLwc.bsv',
]
top = 'lwc'


[[design]]
name = 'verilog'

[design.rtl]
# generator = "xeda run bsc --design-name Ascon"
sources = [
    "gen_rtl/lwc.v",
]
top = "lwc"
clock.port = "clk"

[design.tb]
sources = ["asconTb.py"]
cocotb = true


[flow.bsc]
verilog_out_dir = "${design_root}/gen_rtl"
optimize = true
debug = false
gtkwave_package = "AsconLwc"

