[[project]]
name = "Subterranean 2.0 LWC in Bluespec"
description = "BlueLight implementations"
author = "Kamyar Mohajerani"

[[design]]
name = 'Subterranean'

[design.rtl]
sources = [
    '../bluelight/Bus/BusDefines.bsv',
    '../bluelight/Bus/BusFIFO.bsv',
    '../bluelight/Bus/Bus.bsv',
    '../bluelight/CryptoCore.bsv',
    '../bluelight/LwcApi.bsv',
    'SubterraneanDefs.bs',
    'Utils.bsv',
    'Subterranean.bsv',
    'SubterraneanLwc.bs',
]
top = 'lwc'
parameters.TOP_MODULE_NAME = 'lwc'

[design.tb]
sources = [
    "subterraneanTb.py"
]
cocotb.module = 'subterraneanTb'

[[design]]
name = 'Subterranean_GEN'

[design.lwc]
algorithm = ['subterraneanv1']

[design.rtl]
sources = [
    'gen_rtl/FIFOL1.v',
    'gen_rtl/lwc.v',
    # wrapped:
    # "/nhome/LWC_Benchmarking/unrestricted/_orig_sources_/LWC/hardware/LWC_rtl/NIST_LWAPI_pkg.vhd",
    # '/nhome/LWC_Benchmarking/unrestricted/_orig_sources_/LWC/hardware/LWC_rtl/elastic_reg_fifo.vhd',
    # '/nhome/LWC_Benchmarking/unrestricted/_orig_sources_/LWC/hardware/LWC_rtl/LWC_wrapper.vhd',
]

top = 'lwc'
# wrapped:
# top = 'LWC_wrapper'
clock_port = 'clk'

