[[project]]
name = "Xoodyak in Bluespec"
description = "Part of the BlueLight implementations"
author = "Kamyar Mohajerani"

[[design]]
name = 'Xoodyak'

[design.rtl]
sources = [
    "../bluelight/Bus/BusDefines.bsv",
    "../bluelight/Bus/BusFIFO.bsv",
    "../bluelight/Bus/Bus.bsv",
    "../bluelight/LwcApiDefines.bsv",
    "../bluelight/BluelightUtils.bsv",
    "../bluelight/CryptoCore.bsv",
    "../bluelight/LwcApi.bsv",
    "../bluelight/PISO.bsv",
    "../bluelight/SIPO.bsv",
    'XoodooDefs.bsv',
    # 'SIPO.bsv',
    # 'PISO.bsv',
    'Xoodyak.bsv',
    'XoodyakLwc.bsv',
]
top = 'lwc'
parameters.TOP_MODULE_NAME = 'lwc'

[[design]]
name = 'Xoodyak_BSV_v'

[design.lwc]
algorithm = ['xoodyakv1', 'xoodyakv1']

[design.rtl]
sources = ['gen_rtl/FIFOL1.v', 'gen_rtl/lwc.v']

top = 'lwc'
clock_port = 'clk'

[design.tb]
sources = [
    "../LWC_tb/LWC_config_32.vhd",
    "../LWC_tb/NIST_LWAPI_pkg.vhd",
    "../LWC_tb/LWC_TB.vhd",
]
top = "LWC_TB"


[design.tb.generics]


[[design]]
name = 'Xoodyak2x'

[design.rtl]
sources = [
    "../bluelight/Bus/BusDefines.bsv",
    "../bluelight/Bus/BusFIFO.bsv",
    "../bluelight/Bus/Bus.bsv",
    "../bluelight/LwcApiDefines.bsv",
    "../bluelight/BluelightUtils.bsv",
    "../bluelight/CryptoCore.bsv",
    "../bluelight/LwcApi.bsv",
    "../bluelight/PISO.bsv",
    "../bluelight/SIPO.bsv",
    'XoodooDefs.bsv',
    'Xoodyak2x.bsv',
    'XoodyakLwc.bsv',
]
top = 'lwc'
parameters.TOP_MODULE_NAME = 'lwc'
parameters.UNROLLED = true
